/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCatalog: typeof import('./src/components/app/AppCatalog.vue')['default']
    AppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/app/AppHeader.vue')['default']
    Background: typeof import('./src/components/login/Background.vue')['default']
    Banner: typeof import('./src/components/struct/Banner.vue')['default']
    FormCard: typeof import('./src/components/login/FormCard.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MovieBanner: typeof import('./src/components/movie/MovieBanner.vue')['default']
    MovieCard: typeof import('./src/components/struct/MovieCard.vue')['default']
    MovieCredits: typeof import('./src/components/movie/MovieCredits.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}