// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBanner: typeof import('./src/components/app/AppBanner.vue')['default']
    AppCatalog: typeof import('./src/components/app/AppCatalog.vue')['default']
    AppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/app/AppHeader.vue')['default']
    Background: typeof import('./src/components/login/Background.vue')['default']
    FormCard: typeof import('./src/components/login/FormCard.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginFooter: typeof import('./src/components/login/LoginFooter.vue')['default']
    Logo: typeof import('./src/components/login/Logo.vue')['default']
    MovieCard: typeof import('./src/components/struct/MovieCard.vue')['default']
  }
}

export { }
